### PR TITLE
Add `preserve` and `appendExtensions` options

### PR DESCRIPTION
**Pull request by hgl**

### CODE REVIEW

**Comment by MoOx** [comment]
That's a good start.
Considering https://github.com/postcss/postcss-custom-properties/issues/26#issuecomment-91116710 maybe we should make appendExtensions automatic if preserve is truthy ?

**Comment by hgl** [comment]
I just thought you might need some more time to decide on the new option values.

We can merge this first and then refactor it the same way as we will do for custom properties when the option values is determined.

**Comment by MoOx** [comment]
I just don't want to add an option to remove it in the next release.

**Comment by hgl** [comment]
Thanks for the merging. With the options implemented, we already have to remove them. ;)

**Comment by MoOx** [comment]
Thanks for your contribution.
I am just trying to offer simple API :)

**Pull request merged**
